export default [
  ['[ÁÀÃÂÄ]', 'A'],
  ['[ÉÈÊË]', 'E'],
  ['[ÍÌÎÏ]', 'I'],
  ['[ÓÒÕÔÖ]', 'O'],
  ['[ÚÙÛÜ]', 'U'],
  ['Y', 'I'],
  ['BR', 'B'],
  ['PH', 'F'],
  ['GR|MG|NG|RG', 'G'],
  ['GE|GI|RJ|MJ|NJ', 'J'],
  ['CE|CI', 'S'],
  ['Q|CA|CO|CU|C', 'K'],
  ['LH', 'L'],
  ['RM|GM|MD|SM|AO$', 'M'],
  ['NH', 'N'],
  ['PR', 'P'],
  ['Ç|X|TS|C|Z|RS', 'S'],
  ['LT|TR|CT|RT|ST', 'T'],
  ['W', 'V'],
  ['S$|Z$|R$|M$|N$|AO$|L$', ''],
  ['[AEIOUH]', ''],
];
